### ISSUE TITLE
Suppor human friendly amounts in CLI

### ISSUE THREAD

**Issue by noandrea** [aeternity/aepp-cli-js#120] opened 2019-11-19 11:18 UTC
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the expected behavior?**

Integrate `denomination` feature from SDKwhere possible

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - SDK Version: v7.2.1
  - Environment: nodejs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

https://github.com/aeternity/aepp-sdk-js/issues/382

**Comment by davidyuk** [comment] 2021-12-12 08:17
duplicate of #119

**Closed by davidyuk** 2021-12-12 08:17 UTC
Labels: enhancement
